Kind: Secrets
apiVersion: v1
metadata:
  name: {{ include "dtrack-webhook.fullname" . }}-secrets
  labels:
    {{- include "dtrack-webhook.labels" . | nindent 4 }}
type: Opaque
data:
  DTRACK_API_KEY: {{- if and .Values.env (hasKey .Values.env "DTRACK_API_KEY") -}}
    {{ .Values.env.DTRACK_API_KEY | quote }}
  {{- else -}}
    "DTRACK_API_KEY is required!"
  {{- end }}
  # Add more secrets here as needed
