apiVersion: v1
kind: ServiceAccount
metadata:
  name: dtrack-webhook
  labels:
    app.kubernetes.io/name: dtrack-webhook
    app.kubernetes.io/instance: dtrack-webhook
    app.kubernetes.io/version: "1.0.0"
